function [scenario, egoVehicle] = closing()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.6 and Automated Driving Toolbox 2.0.
% Generated on: 03-Nov-2020 18:03:25

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [41.41 61.52 0;
    41.41 0 0];laneSpecification = lanespec(4, 'Width', 3.5);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [54.81 0 0;
    54.81 61.52 0];marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Dashed')];
laneSpecification = lanespec(3, 'Width', 3.12, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [55 8.757 0;
    -9.167 8.757 0];laneSpecification = lanespec(2, 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [-9.167 -1.753 0;
    55 -1.753 0];laneSpecification = lanespec(2, 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [53.88 -44.83 0;
    53.88 4.3 0];laneSpecification = lanespec(4, 'Width', 3.75);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [39.3 4.3 0;
    39.3 -44.83 0];laneSpecification = lanespec(3, 'Width', 3.2);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [82.61 2.717 0;
    40 2.717 0];laneSpecification = lanespec([1 2], 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [87.31 4.247 0;
    332.3 4.247 0];laneSpecification = lanespec([1 1], 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [340.6 4.247 0;
    384.5 4.247 0];laneSpecification = lanespec([1 1], 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [384.2 221.6 0;
    384.2 -25.51 0];laneSpecification = lanespec([1 1], 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [384.5 6.247 0;
    429.3 6.247 0];laneSpecification = lanespec([1 1], 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1);

% Add the non-ego actors
pedestrian = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [27.7 15.1 0], ...
    'RCSPattern', [-8 -8;-8 -8]);
waypoints = [27.7 15.1 0;
    66.5 14.6 0];
speed = 1.5;
trajectory(pedestrian, waypoints, speed);

pedestrian1 = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [67 17.7 0], ...
    'RCSPattern', [-8 -8;-8 -8]);
waypoints = [67 17.7 0;
    20.8 18 0];
speed = 1.5;
trajectory(pedestrian1, waypoints, speed);

car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [16 -1.6 0]);
waypoints = [16 -1.6 0;
    38.3 -4.5 0];
speed = 30;
trajectory(car1, waypoints, speed);

